import { importProvidersFrom } from '@angular/core';
import {
  LucideAngularModule,
  Activity, AlertCircle, AlertTriangle, AlignLeft, Archive, ArchiveX,
  ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpDown, Atom, Award,
  BadgeCheck, Banknote, Barcode, BarChart3, Beaker, Bell, BookOpen,
  Briefcase, Building2, Calculator, Calendar, CalendarCheck, CalendarClock,
  CalendarDays, CalendarPlus, CalendarX, CalendarX2, Camera, ChartBar,
  Check, CheckCircle, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft,
  ChevronRight, ChevronsDownUp, ChevronsUpDown, CircleDollarSign,
  ClipboardCheck, ClipboardList, Clock, CreditCard, Crown, Download,
  ExternalLink, Eye, File, FileBarChart, FileCheck, FileCheck2, FileDown,
  FilePlus, FilePlus2, FileQuestion, FileSearch, FileSignature,
  FileSpreadsheet, FileText, FileX, Filter, FlaskConical, FolderArchive,
  FolderOpen, GitBranch, GraduationCap, GripVertical, HeartPulse, History,
  IdCard, Inbox, Infinity, Info, Layers, LayoutGrid, LineChart, ListChecks,
  Loader, Loader2, LoaderCircle, Lock, Mail, MapPin, MapPinCheck,
  MapPinHouse, MessageSquare, Minus, Move, Network, NotebookPen, Package,
  Paperclip, Pencil, Phone, PieChart, Plane, Play, PlayCircle, Plus,
  Printer, QrCode, RefreshCw, RotateCcw, Save, ScanLine, Search, Send,
  Sheet, ShieldAlert, Sparkles, Star, Table, Target, TestTube, Thermometer,
  TimerReset, Trash2, TrendingDown, TrendingUp, TriangleAlert, Upload,
  UploadCloud, User, UserCheck, UserMinus, UserPlus, UserX, Users, Wallet,
  Workflow, X, XCircle, Zap,
} from 'lucide-angular';

// Ajouter ici toute nouvelle icône référencée par <lucide-icon name="..."> dans les templates.
export const LucideIconsProvider = importProvidersFrom(
  LucideAngularModule.pick({
    Activity, AlertCircle, AlertTriangle, AlignLeft, Archive, ArchiveX,
    ArrowDown, ArrowLeft, ArrowRight, ArrowUp, ArrowUpDown, Atom, Award,
    BadgeCheck, Banknote, Barcode, BarChart3, Beaker, Bell, BookOpen,
    Briefcase, Building2, Calculator, Calendar, CalendarCheck, CalendarClock,
    CalendarDays, CalendarPlus, CalendarX, CalendarX2, Camera, ChartBar,
    Check, CheckCircle, CheckCircle2, CheckSquare, ChevronDown, ChevronLeft,
    ChevronRight, ChevronsDownUp, ChevronsUpDown, CircleDollarSign,
    ClipboardCheck, ClipboardList, Clock, CreditCard, Crown, Download,
    ExternalLink, Eye, File, FileBarChart, FileCheck, FileCheck2, FileDown,
    FilePlus, FilePlus2, FileQuestion, FileSearch, FileSignature,
    FileSpreadsheet, FileText, FileX, Filter, FlaskConical, FolderArchive,
    FolderOpen, GitBranch, GraduationCap, GripVertical, HeartPulse, History,
    IdCard, Inbox, Infinity, Info, Layers, LayoutGrid, LineChart, ListChecks,
    Loader, Loader2, LoaderCircle, Lock, Mail, MapPin, MapPinCheck,
    MapPinHouse, MessageSquare, Minus, Move, Network, NotebookPen, Package,
    Paperclip, Pencil, Phone, PieChart, Plane, Play, PlayCircle, Plus,
    Printer, QrCode, RefreshCw, RotateCcw, Save, ScanLine, Search, Send,
    Sheet, ShieldAlert, Sparkles, Star, Table, Target, TestTube, Thermometer,
    TimerReset, Trash2, TrendingDown, TrendingUp, TriangleAlert, Upload,
    UploadCloud, User, UserCheck, UserMinus, UserPlus, UserX, Users, Wallet,
    Workflow, X, XCircle, Zap,
  })
);
